version: '2'
services:
    db:
        image: mongo
        ports:
            - "27017:27017"
    web:
        build: .
        command: ["rails","server","-p","3000","-b","0.0.0.0"]
        volumes:
            - .:/myapp
        ports:
            - "3000:3000"
        links:
            - db
