version: '2'
services:
    db:
        image: mongo
        ports:
            - "27017:27017"
    web:
        image: sivertigo/wasepa_web #use image from dockerhub by 'docker pull sivertigo/wasepa_web'
        #build: . #use docker-compose build command 
        command: ["rails","server","-p","3000","-b","0.0.0.0"]
        volumes:
            - .:/myapp
        ports:
            - "3000:3000"
        links:
            - db
